### ISSUE TITLE
More Generic

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#22]
As we discussed this needs to be completely generic, my gut feeling is that the `base(json)` is getting in the way of making this a completely generic function, but we do need to change to code to not directly create each Short object...

https://github.com/clarkj93/Automatic-Review-Console/blob/17df4355b734c9235a39c4c34805da530a37581a/Automatic%20Review/Category.cs#L55

**Comment by clarkj93** [comment]
Altered to the below. ShortEntity and ShortPOI now call an Initialise method which is public, if a SE or SP is constructed with a parameter the initialise method will be called automatically otherwise you need to call the initialise method manually with a string parameter.
` `
  `      public T To<T>() where T: Category, ICategory, new()`
   `     {`
    `        T result = new T();`
     `       result.Initialise(this.json.ToString());`
` `
  `          return result;`
   `     }`
