### ISSUE TITLE
Pass in JSON object

### ISSUE THREAD

**Issue by TycTak** [clarkj93/Automatic-Review-Console#24]
Jon have you considered passing in a json object, you are getting the string passing into the short entity and then parsing it again into a json object, why not just pass in json object?

https://github.com/clarkj93/Automatic-Review-Console/blob/36a6f83bfd220a434b351bd3c88ce9ed3dcf4a9b/Automatic%20Review/Category.cs#L59

**Comment by clarkj93** [comment]
Because when the shortentity or shortpoi is being constructed without the convert method I pass in a string from the constructor, if the initialise only took JObject I would have to convert the string json in the constructor to a JObject and then back to a string also. Either way something has to be converted either to a JObject or to a string.

**Comment by TycTak** [comment]
Agreed leave it as is ;-)
